### ISSUE TITLE
关于分词方法的选择问题

### ISSUE THREAD

**Issue by baobao7766** [baoyongzhang/BigBang#20]
您好：
感觉你的分词效果很好，在代码中看到您在SegmentEngine中使用了在单字符/第三方分词/网络api三种方法中切换，然后用了三种第三方分词工具。因为我也用过其中的几种，单个的效果貌似没有那么好，能不能请问一下您是用什么方法在几种不同的分词方法之间切换的呢？
耽误您一点时间，不胜感激！！！

**Comment by baoyongzhang** [comment]
目前引用了三种第三方分词库，但是只会使用一种，通过 productFlavor 来使用不同的三方库。
关于在 单字符/第三方分词/网络API 的切换，是本地保存了用户选择的配置，对应 CharacterParser、NetworkParser，还有 productFlavor 的源码目录中的 ThirdPartyParser。

**Comment by baobao7766** [comment]
ok，多谢多谢！！！

在 2016年11月7日 上午10:22，Mr.Bao <notifications@github.com>写道：
