### ISSUE TITLE
开启XP支持后，微信闪退，

### ISSUE THREAD

**Issue by jc654123** [baoyongzhang/BigBang#21]
在哪可以学安卓开发啊，希望可以把安卓所有东西都梳理一边，在开始选择性的学习，毕竟“”还能让你都学会”？

**Comment by baoyongzhang** [comment]
闪退问题再详细描述一下场景，操作步骤。

**Comment by aviraxp** [comment]
https://github.com/Tencent/tinker

一般而言，认为这与腾讯的Tinker热修复框架有关。在开机时Xposed会提前加载微信的类，而这与Tinker的修复方法是冲突的。Tinker的最新版本在检测到Xposed后应该是不加载Patch的，但是貌似微信没同步。

**Comment by baoyongzhang** [comment]
是的，tinker 确实会和 xposed 冲突，这个和 BigBang 无直接关系。
